### ISSUE TITLE
Sample code removed?

### ISSUE THREAD

**Issue by teameh** [doo/Scanbot-SDK-Examples-iOS#10]
Why were the iOS samples removed? I've found some bugs in the sample code and would like to contribute by submitting a PR.

**Comment by eddyfrank** [comment]
Hi @teameh,

due to some internal reasons we decided to offer the example app as a ZIP file including the SDK and docs for now. You can download it from our website https://scanbot.io/sdk.html.

Anyway, thanks for your willingness to contribute. You can post a description of bugs you found here.

(I will discuss the topic "contribution to example apps" with the Scanbot team again).

Regards,
Eddy

**Comment by teameh** [comment]
Ok, thanks for the response. It just makes contributions, questions about unclear things, and quicker support easier. It might even help your community / engage more users. 

The stuff that I found was mainly documentation related. I might post them later. Thanks.
