### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by thediary** [doo/Scanbot-SDK-Examples-iOS#4]
I get the following errors when building…
<img width="748" alt="screen shot 2015-07-20 at 2 28 26 pm" src="https://cloud.githubusercontent.com/assets/13370443/8787915/b43a173a-2eeb-11e5-8159-2e3874a55f44.png">

I built the project using Xcode 7 Beta 3 (required for our as it targets iOS 9), but the problem is also present in Xcode 6.4 as far as I can tell (still get the same errors even when building there.) and my license is added in the AppDelegate.m file.

Thanks for addressing this!

**Comment by thediary** [comment]
Looks like the majority of these only occur when running in the simulator. Here is all I get when building for device. A bit code issue. Is there a way to include bit code support in the SDK in the near future so that when I incorporate the SDK into my own app that will need bit code support, everything will be functional?
Thanks
 
<img width="777" alt="screen shot 2015-07-20 at 2 37 43 pm" src="https://cloud.githubusercontent.com/assets/13370443/8788156/4cda8492-2eed-11e5-84f2-062f9cc5ff38.png">

**Comment by sebastato** [comment]
Hi thediary,

Thanks for your feedback. 
We just updated the master branch to include i386 and x86_64 archs in the framework.
It doubles the size of the framework and it also increases your app about 20 MB but should run on simulators. We will have to find a final solution. The SDKs static libs are separated already. Using them instead the framework keeps the app small and runs on both, device and simulator.
Not sure if this is possible with embedded frameworks too. Gonna have to research a little. If you have an idea please let me know.

You'll find the updated SDK here: 
https://github.com/doo/Scanbot-SDK-Examples-iOS/tree/master/DocumentDetectionDemo/ScanbotSDK

Regarding bitcode we will check tomorrow if we can build and run with bitcode enabled. In the meantime please try compiling without bitcode. You could also try to sport the static libraries instead of the framework. No idea yet, if this will let you create bitcode.

**Comment by sebastato** [comment]
Update: 
Added both SDK Frameworks: one large for all architectures:
https://github.com/doo/Scanbot-SDK-Examples-iOS/tree/master/DocumentDetectionDemo/ScanbotSDK/Framework/All_Archs

and one for devices only (release):
https://github.com/doo/Scanbot-SDK-Examples-iOS/tree/master/DocumentDetectionDemo/ScanbotSDK/Framework/Device_Only

Embed only one framework. For testing and developing the All_Archs and for Release you would embed the Device_Only framework.
